### ISSUE TITLE
Trouble with running npm run dev

### ISSUE THREAD

**Issue by marcopared** [IgorKowalczyk/igorkowalczyk.github.io#553]
Following local hosting instructions and running npm run dev could give the following error for users on Windows:
![image](https://github.com/IgorKowalczyk/igorkowalczyk.github.io/assets/39688188/3869e88a-e420-47b2-baac-1ebf0366a9e6)

Running npm install -g win-node-dev will fix the issue (source: https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman)

Just a recommendation to add the instruction in case anyone else has the same issue on windows

**Comment by IgorKowalczyk** [comment]
Thank you! However, I think that adding an example for windows is unnecessary, this project is designed to only run on Linux
